### ISSUE TITLE
Validations input advise

### ISSUE THREAD

**Issue by carloso0114** [ArthurGC/awesome-books-project#5]
`const requireInputs = () => {
  if ((title.value.trim() === '') && (author.value.trim() === '')) {
    title.className += ' error';
    author.className += ' error';
    return false;
  }

  if (title.value.trim() === '') {
    title.className += ' error';
    return false;
  }

  if (author.value.trim() === '') {
    author.className += ' error';
    return false;
  }
  return true;
};`
Since the form is taking empty spaces as characters, the trim method will erase those spaces from the beginning and from the end of the input text.
It will do the trick 

![gif](https://i.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.webp)

**Comment by ArthurGC** [comment]
![](https://img.shields.io/badge/Microverse-blueviolet)
# Awesome Books Project 
Thanks for your suggestion.
https://github.com/ArthurGC/awesome-books-project/blob/6457bbd719a426bed9b860eb9aa8792bf5b89fcf/src/app.js#L36-L57
